### ISSUE TITLE
Client crash when looking at uses for blocks

### ISSUE THREAD

**Issue by ukdunc** [b0bst3r/Superstitions#1]
Hey bob - when pressing "u" over a block of glowstone or a block of clay today (only 2 I tested) and then clicking through the different options e.g. craft, smelt, macerate etc, one of next screens from one of the mods I guess caused the client to crash.

**Comment by b0bst3r** [comment]
Crashlog?

**Comment by ukdunc** [comment]
[crash-2016-09-30_14.00.06-client.txt](https://github.com/b0bst3r/Superstitions/files/504106/crash-2016-09-30_14.00.06-client.txt)
[crash-2016-09-30_14.54.31-client.txt](https://github.com/b0bst3r/Superstitions/files/504107/crash-2016-09-30_14.54.31-client.txt)
