### ISSUE TITLE
Client crash on attempting to craft Silent's Gems armor

### ISSUE THREAD

**Issue by Myriadtail** [b0bst3r/Superstitions#10]
I put the four gems into the crafting table, put the armor frame in the middle, and it shows up as craftable.  I attempt to get the armor, and my client crashes on the spot.  Not sure if this is a pack-specific crash, or something that should be reported to Silent's Gems modauthor.

[crash-2016-11-26_21.37.53-client.txt](https://github.com/b0bst3r/Superstitions/files/614552/crash-2016-11-26_21.37.53-client.txt)

**Comment by b0bst3r** [comment]
vanilla crafting table?

**Comment by Myriadtail** [comment]
Correct. Though I had to start a new world since I corrupted it with something else.

**Comment by b0bst3r** [comment]
I'd like to know what that was the "something else"?

**Comment by Myriadtail** [comment]
Integrated Dynamics, placing a Fluid Interface below a Squeezer causes a crash.


[crash-2016-11-27_22.49.53-server.txt](https://github.com/b0bst3r/Superstitions/files/615402/crash-2016-11-27_22.49.53-server.txt)

**Comment by b0bst3r** [comment]
I created a new issue for the ID/Squeezer crash, please report everything.

**Comment by superfluke** [comment]
Had the same crash with making gem armor in a vanilla crafting table. You can use the rftools crafter without a crash if you want a workaround in the meantime.

**Comment by b0bst3r** [comment]
Yeah just waiting for a release to fix this.

**Comment by b0bst3r** [comment]
Fixed in 1.6.3
