### ISSUE TITLE
Can't throw redstone from inventory. Prevents flux creation. 

### ISSUE THREAD

**Issue by superfluke** [b0bst3r/Superstitions#14]
Redstone thrown from inventory is sucked back in as if the player is wearing a magnet. Bug occurred on a server, confirmed by a couple players. This prevents the creation of flux which needs redstone thrown into a fire. Version 1.6.2

**Comment by b0bst3r** [comment]
I'm playing on a server right now and can throw redstone just fine, can you retry in single player, it may have been a mod I've updated since.

**Comment by superfluke** [comment]
I will test that out and see if the server will update. 
Also, don't know if this was intended but the new treated  wood recipe only returns 1 treated wood for the 8 undead planks required rather than the normally 8 returned. While I'm poking around in the configs, noticed you removed the base metals steel blend for being too easy, however the ability for players to cook iron nuggets into steel nuggets remains.

**Comment by b0bst3r** [comment]
treated wood ...... how did that happen I havent' changed ANY scripts since launching the pack......

**Comment by superfluke** [comment]
Sorry I meant the treated wood recipe new to this pack. Every version has returned 1 treated wood rather than 8. 

Updated to 1.6.4 still can't throw redstone on the ground.

**Comment by b0bst3r** [comment]
I don't have any issues throwing redstone if you throw it far it still gets sucked back in?  In SSP too?

**Comment by superfluke** [comment]
Looks to be working fine in ssp. Even dropping stacks while on multiplayer is acting up or flying up and throwing straight down. Also ejecting it from a dispenser causes it to eject and slingshot back to the dispenser opening. Getting a similar behavior with eyes of ender. When they turn back into an item to drop, they start to fall but before hitting the ground they slingshot back to where they started their fall.

**Comment by devanchya** [comment]
works fine on my server
