### ISSUE TITLE
Steam compression assembler broken 

### ISSUE THREAD

**Issue by superfluke** [b0bst3r/Superstitions#15]
Tested in both multiplayer and single player 1.6.4.

**Comment by superfluke** [comment]
Fat fingers hit submit before I was done typing. Problem is with the steam compression assembler for inductive automation. Cannot get any output from the machine and some slots don't seem to be accepting items in. It's possible I'm using this mod wrong but it's hard to find any info other than the pdf manual. Prevents not only inductive automation but also quantum flux and late game calculator recipes

**Comment by b0bst3r** [comment]
What items are you trying to put in?

**Comment by superfluke** [comment]
I've tried a few. Like the stuff need to make the conductive alloy dust. When that didn't work I tried putting just iron in the top left to make powdered iron, then tried 4 iron in the bottom right and the machine wouldn't even accept it. Have you tried using it?

**Comment by b0bst3r** [comment]
I can't replicate this at all, please be aware that the recipes for all Inductive Automation machines require the items in the slots specified in the recipe.  So for conductive alloy dust it's 2 redstone (top left) 1 electrum ingot (top right)  2 copper ingot (bottom left) and 1 iron ingot (bottom right).  

Works fine in SSP and SMP here.

**Comment by superfluke** [comment]
Looks like it was a known bug. Got fixed in inductive automation 5.3.1
