### ISSUE TITLE
oredict recipes for extreme reactors

### ISSUE THREAD

**Issue by DoomSquirter** [b0bst3r/Superstitions#16]
latest on atl and on tybak server

To make the reactor casing (legacy) the thing requires a casing core, which properly oredicts graphite so you can make them, but the actual casing itself is requiring the specific graphite from the extreme reactors mod itself, not oredict.  

You can't make the extreme version cause it requires graphite to make it from block form, etc.

Probably more than just that bit that needs the oredicting.

**Comment by b0bst3r** [comment]
Fixed in 2.0.0 (version change so as not to clash with MC versions)
