### ISSUE TITLE
Town Hall is permanent

### ISSUE THREAD

**Issue by TheUberCannon** [b0bst3r/Superstitions#17]
When I decided to make a town, I realized the area I picked wasn't good enough. So I decided to move the town hall and found an extreme hills with nice and flat areas to build in but seeing as the residents persisted, and it says "You have placed a town hall already" without it in the world at all anymore now renders the whole mod useless. Not even placing the hall back would fix it.

Possibly because the hall was selected in the build queue before I decided to take the hall with me.

**Comment by b0bst3r** [comment]
You have to delete your colony which is done via command line.

/mc colonies list 
/mc colony delete 

I believe, I haven't actually tried it.

**Comment by TheUberCannon** [comment]
Many thanks, did this via the "Open to LAN" button.
