### ISSUE TITLE
Kenetic Shaft - Recipe Conflict

### ISSUE THREAD

**Issue by devanchya** [b0bst3r/Superstitions#19]
Release 2.4.1 - Kenetic Shaft Conflict
Currently the recipe is:

 X X X
(Iron Ingot) (Iron Ingot) (Iron Ingot)
X X X

This conflicts with BaseMetas:IronPlate

basemetals.zs fix:
`// remove conflicting basemetals plate
recipes.remove(<basemetals:iron_plate>);
recipes.addShaped(<basemetals:iron_plate> * 3,                     [[null,null,null],
                                                                                                        [<ore:ingotIron>,<ore:ingotIron>,<ore:ingotIron>],
                                                                                                        [null,null,null]]);
`

new automation.zs:
`// Remove the old Shaft Recipe
recipes.remove(<automation:shaft>);
// Custom One to not compete with the Base Metals Plates
recipes.addShaped(<automation:shaft> * 2,                     [[null,null,null],
                                                                                                        [null,null,null],
                                                                                                        [<ore:ingotIron>, <ore:ingotIron>,<ore:ingotIron>]]);`

**Comment by b0bst3r** [comment]
You know the pack has nomorerecipeconflict mod right? :)
