### ISSUE TITLE
Client crash and can't log back in when Robit (Mek) right clicked on charge pad

### ISSUE THREAD

**Issue by ukdunc** [b0bst3r/Superstitions#2]
[crash-2016-10-03_16.59.51-client.txt](https://github.com/b0bst3r/Superstitions/files/506669/crash-2016-10-03_16.59.51-client.txt)

**Comment by b0bst3r** [comment]
After reading that crashlog again seems it might be WAILA

**Comment by b0bst3r** [comment]
Confirmed it's WAILA, removed from server and client = no crash.

**Comment by ukdunc** [comment]
Legend - thanks mate xxx

**Comment by ukdunc** [comment]
Sorry mate still crashing - log attached.  It loaded and logged me in - my base opened up in front of Robit then froze and crashed.

[crash-2016-10-03_20.07.29-client.txt](https://github.com/b0bst3r/Superstitions/files/506993/crash-2016-10-03_20.07.29-client.txt)

**Comment by b0bst3r** [comment]
Yeah cos you left Waila and addons loaded in your client

**Comment by b0bst3r** [comment]
I can either trash the robit and you not use one again or you trash waila and use theoneprobe and keep the robit.

**Comment by ukdunc** [comment]
oh ok sorry!

**Comment by ukdunc** [comment]
I:needsProbe=0 iS already set in my config - should that be all I need to do?  Just remoed the 2 waila mods

**Comment by b0bst3r** [comment]
Removing Waila and Waila Harvestability in next update.

**Comment by b0bst3r** [comment]
Since this happens with both Waila and TheOneProbe I'm keeping it open

**Comment by b0bst3r** [comment]
Update to the OneProbe in 1.41 should fix this crash
