### ISSUE TITLE
server crash when firing Beam Cannon from Embers

### ISSUE THREAD

**Issue by meradudd** [b0bst3r/Superstitions#20]
So, trying to get the Beam Cannon/Exchange Tablet alchemy setup working in Embers.  Whenever I fire off the Beam Cannon, I get the server crash below.  Used MC edit to remove the lever (redstone signal needed to fire the Cannon) and it loads fine.  Moved Beam Cannon retested with same result.  Help?

[crash-2017-01-09_21.02.08-server.txt](https://github.com/b0bst3r/Superstitions/files/695258/crash-2017-01-09_21.02.08-server.txt)

**Comment by meradudd** [comment]
Great googlie-mooglies B0bst3r.  If you were any faster, you'd have the troubles fixed before people told you about them.  Thanks ever so for the speedy fix.

Pax.

Mer.

**Comment by b0bst3r** [comment]
The update is on hold until this is addressed - https://github.com/RootsTeam/Embers/issues/64
