### ISSUE TITLE
[Linux] Can't connect to server: Missing blocks and items

### ISSUE THREAD

**Issue by alex-eg** [b0bst3r/Superstitions#25]
Bevos 3.2.0 on Minecraft 1.10.2

Can't connect to the server running same version with the following error:
http://paste.atlauncher.com/view/19747182

Windows client works just fine.
Before the last update everything was fine.

**Comment by b0bst3r** [comment]
Update server and client to be on same configs, that's caused by a mismatch in client/server configs.

**Comment by alex-eg** [comment]
They were on the same config, of course.

That issue was because of case mismatch between path somewhere inside client config file and path in the filesystem, which is critical for case-sensitive filesystems, like ext4 I use on Linux.

NTFS is not case-sensitive, so on WIndows that issue hadn't manifested itself.


Sorry I haven't written here about my findings earlier.
Please note that case mismatch between paths in config and on the disk may cause such errors.
