### ISSUE TITLE
planter from Agri. revolution, converts birch saplings to oak

### ISSUE THREAD

**Issue by StrommKral** [b0bst3r/Superstitions#28]
when inserting birch saplings into the planter from the agricultural revolution it changes them to oak saplings. never tried with other saplings

**Comment by StrommKral** [comment]
reproduced this with the other saplings too

**Comment by b0bst3r** [comment]
Can't do anything about this, it's fixed in later versions but the modder decided to change his entire block/item IDs after the version we use.  If I update everything agri rev would disappear and you'd need to start new worlds/map.
