### ISSUE TITLE
recipe for moonstone (exu2)?

### ISSUE THREAD

**Issue by DoomSquirter** [b0bst3r/Superstitions#3]
Since moonstone is so incredibly rare, maybe a recipe for it?  Even if it's outlandish like 8 different supercharged gems or 8 chaos cores or something?  It's only used in ethereal glass (the moonstones).

if you're feeling lenient, even a silent gems moonstone -> oredict to gemMoon for exu2 maybe.  but yeah, running that exu2 quarry for a day even with just fortune on it not silk (silk might be a problem with that particular block) I've yet to get one with it.  I found another while digging out something so I ended up with 2 total moonstones since start of map.

**Comment by b0bst3r** [comment]
Since Tema never answers me or posts on his github I don't know if this is a feature, or planned, or a bug that needs fixing, or ........ < insert something else here.

So I plan on adding an additional recipe to use supercharged moonstone gems as well as the Ex Ut moonstone.

**Comment by b0bst3r** [comment]
Check if you get any more moonstone in the update which is coming.

**Comment by b0bst3r** [comment]
Can't add a recipe for moonstone, minetweaker sees no recipe to insert and it's not working whichever way I try.

**Comment by b0bst3r** [comment]
Added additional Effable glass recipes
