### ISSUE TITLE
Embers Item Pipes uncraftable.

### ISSUE THREAD

**Issue by TwilightWalker** [b0bst3r/Superstitions#31]
As the title says, item pipes form Embers are uncraftable due to what looks like a copy and paste error in the embers.zs script labelling the replacement as IronPipes, as follows: 

//Item Pipe
recipes.remove(ItemPipe);
recipes.addShaped(IronPipe *8,				[[LeadPlate, CaminitePlate, LeadPlate]]);

**Comment by b0bst3r** [comment]
Fixed in 4.2.0 along with a few other things
