### ISSUE TITLE
putting this out here even tho it's a bug/feature - saplings @ forestry @ EIO farming station

### ISSUE THREAD

**Issue by DoomSquirter** [b0bst3r/Superstitions#6]
so, been noticing that sometimes my eio farming station stops planting saplings and is completely out and couldn't figure out why.  

Looked into fae just now and realized for example, I have a bunch of oak saplings, but also a equivalent bunch of oak APPLE saplings from forestry.  same for birch and silver birch.  

So I guess forestry's dropping the other saplings randomly?  Didn't forestry require you to do something with a grafter before you started getting those different forestry types?

**Comment by b0bst3r** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3744 It's fixed already just waiting on a build

**Comment by b0bst3r** [comment]
Fixed in update
