### ISSUE TITLE
add a sag mill/mek/actually additions recipe for ender dust for ae2

### ISSUE THREAD

**Issue by DoomSquirter** [b0bst3r/Superstitions#8]
right now, only recipe is the grindstone from ae2.  usually there's at least a sag mill 1:1 recipe, one ender pearl == one ender dust, etc.  or if there's another ender dust-ish thing, add oredict to it for the wireless boosters or whatever else uses them for recipes.

**Comment by b0bst3r** [comment]
Fixed in 1.5.6
